
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EURODAY = 12;
  public static final int CP = 7;
  public static final int OP = 6;
  public static final int COLON = 8;
  public static final int SCOLON = 10;
  public static final int ELECTRICITY = 14;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int DOT = 11;
  public static final int UINT = 16;
  public static final int QSTRING = 15;
  public static final int MIN_SUM = 13;
  public static final int REAL = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "OP",
  "CP",
  "COLON",
  "COMMA",
  "SCOLON",
  "DOT",
  "EURODAY",
  "MIN_SUM",
  "ELECTRICITY",
  "QSTRING",
  "UINT",
  "REAL"
  };
}

